<%@ page language="java" contentType="text/html; charset=EUC-KR"
    pageEncoding="EUC-KR"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=EUC-KR">
<title>Insert title here</title>
</head>
<body>
                    - 2016년 정규직 신입사원 모집공고 : 개발/영업 부문 -<br><br>(주)SPH는 2011년 5월 한국에서 처음으로 Google Geo부문 Enterprise Partner로 활동을 시작한 후<br>2016년 현재 한국내 유일한 Google Geo Premier Partner사로서 많은 기업들에게 영업 및 마케팅 활동을 하고 있습니다.<br>또한 2013년부터 SuperMap의 한국총판으로 공공 및 민간기업에 GIS SW를 판매하고 기술지원을 하고 있으며<br>2016년 부터는 스페인과 미국 뉴욕에 본사를 두고있는 CartoDB의 한국 Reseller로 새로운 시장개척을 준비하고 있습니다.<br><br>이에 열정을 가진 정규직 신입사원을 충원하여 기존의 Google API와 GIS SW 및 새로운 제품군의 Web, Mobile 서비스 기술개발과 국내외 새로운 시장개척에 함께 할 개발직군, 영업직군의 정규직 신입사원을 모집합니다.<br><br>SPH는 작지만 강한 회사이며 일과 삶의 균형을 중시하는 문화를 가진회사로 아래와 같은 근무조건과 복지정책을 갖고 있습니다. <br><br>- 근무시간<br>▷ 일일7시간 근무 : 오전10시 ~ 오후6시 (월~금) , 주35시간<br><br>- 근무조건 및 복지 <br>▷ 동종업계 상위수준의 년봉지급<br>▷ 여의도 일대 맛집 점심식사 제공<br>▷ 대외세미나, 컨퍼런스 참석지원<br>▷ 최신사양 맥북 혹은 Laptop 제공(본인 선택)<br>▷ 영어등 외국어교육, 헬스비 지원, 2년마다 건강검진<br>▷ 매년 성과에 따른 인센티브를 4년째 지급 함<br>▷ 우수사원 해외 Google, SuperMap, CartoDB 교육참가 지원<br>▷ 매 3년이상 장기근속시 Refresh 1개월 유급휴가 (최근 영국, 프랑스, 호주등 여행으로 사용)<br><br>1. 모집분야<br><br>1)개발직군 신입직원 1명<br><br>- 4년제대학 전산관련 학과 졸업자(예정자) 및 6개월과정의 전문학원 이수자<br>- 새로운 정보를 찾아보고 적용하는것에 흥미가 있고 Web 및 Mobile 신기술 연구에 관심이 많은 분<br>- 사용기술 : JavaScripts, HTML5, CSS, Java, Google API, Open Source, Android iOS Mobile 기술<br><br>2) 영업직군 신입직원 1명<br><br>- 4년제대학 졸업자(예정자)로 전공, 성별 무관<br>- 평소에 구글맵과 같은 디지털맵에 관심이 많으신 분<br>- 새로운 사람을 만나서 대화하는 일에 즐거움을 느끼시는 분<br>- GIS S/W 및 Web Service 공공,기업 대상 기획, 제안, 영업<br><br>2. 공통사항 <br><br>- 열정적인 자세와 호기심, 부당함에 눌리지 않는 강단, 잘난척 하지않는 겸손함, <br>- 따뜻한 미소, 긍정적인 에너지, 포기하지 않는 성실함, 충실한 기본기<br>- 해외 본사의 R&amp;D, 마케팅, 영업 부문과의 교류를 위한 커뮤니케이션 능력<br>- Google APAC과의 커뮤니케이션 (영어)<br>- SuperMap 베이징 본사와의 커뮤니케이션 (영어,중국어)<br>- CartoDB 뉴욕, 마드리드 본사 커뮤니케이션 (영어, 스페인어)<br><br><br>3. 우대사항<br>영업직군은 해외본사와의 미팅이 비정기적으로 있고 새로운 해외 시장개척을 위해 일정 수준급의 영어 스킬을 필요로 합니다.<br>개발직군은 영어가 필수는 아니지만 기술지원과 문의를 위한 영문 이메일작성과 기본소통수준의 영어 스킬은 필요로 합니다.<br><br>중국어와 스페인어도 필요하나 필수사항은 아니며 우대합니다.<br><br><br>4. 지원방법<br>제출서류 : 이력서 및 역량위주의 핵심적인 자기소개 : 자유형식, MS-Word 파일<br>지원방법 : 이메일로 접수함 ( job@sphinfo.co.kr )<br>제출기한 : 2016년 1월 31일까지 (합격자 채용시 조기종료)<br>합격발표 : 개별 이메일로 서류합격여부 통보 및 면접<br>모집대상 : 대학교 재학중인 4학년 또는 2016년 졸업자<br><br>이력서와 면접만으로 충분한 역량을 알 수 없다고 판단되고 또한 입사희망자도 어떤회사인지 금새 판단하기 어려울 수 있습니다. <br>따라서 저희회사는 2개월의 인턴기간을 두고 있으며 이 기간동안 역량이 검증되고 상호 문화적인 코드가 맞다면 정규직으로 전환됩니다. 인턴기간동안 급여는 월130만원이며 근무시간은 오전10시 ~ 오후6시이고 점심식사 및 노트북도 동일하게 제공됩니다.<br><br>5. 홈페이지<br><br>홈페이지 : http://www.sphinfo.com , http://www.supermap.co.kr<br>블로그&nbsp;&nbsp;: http://www.sphinfo.com/blog , http://blog.naver.com/supermap2013<br>페이스북 : http://facebook.com/googlemapskorea<br><br><br><br>2016년 SPH와 스토리(Story)를 만들어 낼 분들의 많은 응모 바랍니다.<br><br><br>(주)SPH , Story Place &amp; Human<br>서울시 영등포구 여의도동 25-5 동화빌딩 13층<br>
                
</body>
</html>